# Generated by Django 4.1.7 on 2023-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Аккаунт клиента', 'verbose_name_plural': 'Аккаунты клиентов'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Ник'),
        ),
    ]
