# Generated by Django 4.1.7 on 2023-02-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
